title: Jonathan's Site
description: Find Your Favourite High Quality Exploits Here
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
